services:
  database:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: e_commerce_microservices,keycloak
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        aliases:
          - "database"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB-USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: ${KC_DB_URL}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
    command: ["start-dev"]
    networks:
      backend:
        aliases:
          - "keycloak"

  zookeeper:
    image: zookeeper:3.7.2
    restart: always
    ports:
      - "2181:2181"
    networks:
      backend:
        aliases:
          - "zookeeper"

  config-service:
    container_name: config-service
    image: e-commerce/config-service:latest
    build:
      ../config-service
    restart: always
    environment:
      CONFIG_DIR: /app/data
      GIT_CONFIG_REPO_URI: ${GIT_CONFIG_REPO_URI}
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_PASSWORD: ${GIT_PASSWORD}
    networks:
      backend:
        aliases:
          - "configservice"

  discovery-service:
    container_name: discovery-service
    image: e-commerce/discovery-service:latest
    build:
      ../discovery-service
    restart: always
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
      CONFIG_SERVICE_HOSTNAME: config-service
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8761:8761"
    networks:
      backend:
        aliases:
          - "discoveryservice"

  gateway-service:
    container_name: gateway-service
    image: e-commerce/gateway-service:latest
    build:
      ../gateway-service
    restart: always
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
      CONFIG_SERVICE_HOSTNAME: config-service
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - product-service
      - keycloak
    ports:
      - "8765:8765"
    networks:
      backend:
        aliases:
          - "gatewayservice"

  product-service:
    container_name: product-service
    image: e-commerce/product-service:latest
    build:
      ../product-service
    restart: always
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
    env_file:
      - "./services-env"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - "8081:8081"
#    links:
#      - config-service
#      - discovery-service
#      - database
#      - keycloak
    networks:
      backend:
        aliases:
          - "productservice"

  order-service:
    container_name: order-service
    image: e-commerce/order-service:latest
    build:
      ../order-service
    restart: always
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
    env_file:
      - "./services-env"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - "8082:8082"
    links:
      - config-service
      - discovery-service
      - database
      - keycloak
    networks:
      backend:
        aliases:
          - "orderservice"

  user-service:
    image: e-commerce/order-service:latest
    build:
      ../user-service
    restart: always
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
    env_file:
      - "./services-env"
    depends_on:
      database:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - database
      - keycloak

volumes:
  pgdata:
    name: "pgdata"

networks:
  backend:
    driver: bridge