services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak123
    command: start-dev

  elastic-search:
    container_name: elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=123123
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    mem_limit: 1GB
    networks:
      - elastic

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  elastic: