spring:
  application:
    name: "order-service"

  config:
    import: "configserver:http://${CONFIG_SERVICE_HOSTNAME}:8888"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/realms/E-Commerce"