spring:
  application:
    name: "config-service"

  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_REPO_URI}
          clone-on-start: true
          basedir: ${CONFIG_DIR}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

        default-label: master

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "${DB_DRIVER}"

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"